# Site settings
title: Georgios Mintzopoulos
twitter_username: mintzopg
name: Georgios Mintzopoulos

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: 
 - title: GitHub
   url: https://github.com/mintzopg
 - title: StackOverflow
   url: http://stackoverflow.com
 - title: DZone
   url: https://dzone.com
 - title: LinkedIn
   url: https://www.linkedin.com

#Any buzzword skills you want to include
skills:
 - Python
 - Javascript
 - Java
 - R
 - HTML/CSS
 - SQL
 - Tech 

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: http://automateddeveloper.blogspot.com/feeds/posts/default?alt=rss

#Work experience is required
roles:
 - title: Senior Account Manager
   start: 2007
   end:   2013
   employer: Italtel SpA
   description: <strong>...</strong>
 - title: Telecommunications Engineer
   start: 1998
   end: 2006
   employer: Intracom Telecoms SA
   description: <strong>...</strong>
 
#Education is required
education:
 - level: Diploma in Electrical & Computer Engineering
   date: 1996
   subject: Control Systems
   school: University of Patras

#This section is optional (as is the image link below)
coursera:
   profileurl: 
   courses:
    - title: Functional Programming Principles in Scala
      link: https://www.coursera.org/course/progfun
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      date: August, 2016
    
#List of interesting Github repo/projects to include - optional
# github:

#Stackoverflow flair is optional
# stackoverflow:
   
#Mobile apps section is optional
# apps:

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   
